index:
    path: /
    controller: App\Controller\FilmController::displayFilms

add:
    path: /add
    controller: App\Controller\FilmController::new

success:
    path: /success
    controller: App\Controller\FilmController::success

error:
    path: /error
    controller: App\Controller\FilmController::error

delete:
    path: /delete
    controller: App\Controller\FilmController::delete